### ISSUE TITLE
Combo/ Size mismatch

### ISSUE THREAD

**Issue by Sparkleunicorn9** [jolars/eulerr.co#1]
Hey, 
I was looking into how this works for a project i'm working on that's really similar. 
When i tried to replicate using your code (ui.R and server.R) and rand the app, the combos are off. 
With just A,B and A&B : A is correct, B is A&B and A&B is B. 
If I add an additional label (D) D has the size of A, D becomes size B, A&B becomes the value of B etc. 

Do you have any idea what is going on here? 

Many Thanks

**Comment by jolars** [comment]
It is very hard to say without having anything more to go on.

**Comment by Sparkleunicorn9** [comment]
I've copied the files exactly as they are:
ui.R 
server.R 

The result is the image below: 
![image](https://user-images.githubusercontent.com/54576754/79208918-a20a2c00-7e3a-11ea-92e1-3acc1c7255ab.png)

The input and chart do not match. 

Please let me know if any further information would be valuble

**Comment by jolars** [comment]
What version of eulerr are you running?

**Comment by Sparkleunicorn9** [comment]
6.1.0

**Comment by jolars** [comment]
Ah, I can reproduce this locally here too. I'll see what I can do.
