### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ellyyuyang** [jolars/eulerr.co#2]
Hello, thanks for developing this awesome tool!!
I have been experiencing "502 Bad Gateway nginx/1.10.3 (Ubuntu) " when trying to access your website since 24hr ago. I have cleared my browsing caches and cookies, restarted my computer, but still getting this error when trying to access your website. I am wondering if there is anything else I should try to resolve this issue? Thanks, much appreciated!

**Comment by jolars** [comment]
Thanks for reporting but I think it's something on your end. It works fine for me and see this: <https://www.isitdownrightnow.com/eulerr.co.html>
