### ISSUE TITLE
Site offline & question re: re-use

### ISSUE THREAD

**Issue by will-ball** [jolars/eulerr.co#3]
Hi Johan,

I'm looking to create an interactive presentation of some research results and came across your interesting looking project. I've noticed that the www.eulerr.co website is no longer active (502 Bad Gateway error) which is a shame. It looked like an excellent app.

I was hoping that I might be able to use and adapt your shiny code for my project (with attribution of course). Is that okay?

Thanks,
Will

**Comment by jolars** [comment]
Is it? Strange. It seems to work for me!

But sure. You are free to use it. The app is licensed using GPL-v3.
